name: Publish Package

on:
    push:
        branches:
            - master

jobs:
    biome:
        name: Create Release
        if: ${{ contains(github.event.head_commit.message, 'chore(release):') }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: to NPM
              run: bun publish --registry=https://registry.npmjs.org
              env:
                  NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: to GitHub
              run: bun publish --registry=https://npm.pkg.github.com
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
